<?php

/**
 * Syncs your user list with Mailchimp
 *
 * Copyright (C) 2011 by Stephen Tomlinson 
 * 
 * http://makeinteractive.co.uk
 *
 */
 
require_once("MCAPI.class.php");

class MailChimpSync extends WireData implements Module, ConfigurableModule {

	/**
	 * Basic information about module
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'MailChimp Sync', 
			'version' => 100, 
			'summary' => 'This module syncs your user list with MailChimp',
			'singular' => true,
			'autoload' => true, 
			);
	}
	
	/**
	 * Default configuration for module
	 *
	 * This is based on Ryan's examples [used also in @apeisa's AdminBar, for instance]
	 */
	protected static $defaultConfigData = array(
		'apiKey' => false,
		'listId'	=> false,
		'email' =>	false,
		'fname'	=>	false,
		'lname'	=>	false,
		'otherFields'	=>	false,
	);
	
	/**
	 * Populate the default config data
	 *
	 */
	public function ___construct() {
	   foreach(self::$defaultConfigData as $key => $value) {
		   $this->$key = $value;
		   $data[$key] = $value;
	   }
	}

	/**
	 * Initialize the module
	 *
	 */
	public function init() {
		wire('pages')->addHookAfter('saveReady', $this, 'hookAfterSaveReady');	
	}
	
	/**
	 * To be run whenever a user is saved
	 *
	 */
	public function hookAfterSaveReady(HookEvent $event) {

		$user = $event->arguments[0];
    
		// Only handle users
		if(!$user instanceof User) return;
    
    // If the user is new, add them to the list
    if($user->isNew()) {
      $this->addSubscriber($user); 
      return true;
    }
		
    // If they have changed their details upate them (we should only check the required fields here!)
		if($user->isChanged()) $this->updateSubscriber($user);
    
	}
	
	/**
	 * Sync the user with the list. If they do not have the correct role, no action is taken
	 *
	 */
	public function updateSubscriber(User $user) {
	
		$api = new MCAPI($this->apiKey);
    
    // Setup PW Roles as groups on MailChimp
    $this->setupGrouping();
    
    // The user's roles
    $groupsArr = array();
    foreach($user->roles as $role) {
      $groupsArr[] = $role->name;
    }
    $groups = implode(",", $groupsArr);
    			
		// Set the fields to update
    $email = $user->email;
		$merge_vars = array(
      "FNAME" => $user->get($this->fname),
      "LNAME" => $user->get($this->sname),
      "GROUPINGS" => array(array('name' => 'Role', 'groups' => $groups))
    );
    
    // Has their email changed?
    if($user->isChanged('email')) {
      wire('pages')->uncacheAll();
      $email = $this->pages->get($user->id)->email;
      $merge_vars['NEW-EMAIL'] = $user->email;
      $this->message("Old: $email, New: {$merge_vars['NEW-EMAIL']}");
    }
		
    // Update the user with the mailchimp API
    
		$double_optin = false;
		$update_existing = true;
		$replace_interests = true;
		$send_welcome = false;
		
		$retval = $api->listSubscribe($this->listId, $email, $merge_vars, 'html', $double_optin, $update_existing, $replace_interests, $send_welcome);
		
		// Report any errors
    
		if ($api->errorCode){
      $this->message("MailChimp: ({$api->errorCode}) {$api->errorMessage}");
		} else {
		  $this->message("Updated with MailChimp");
		}
    
    return $retval;
		
	}
  
	public function addSubscriber(User $user) {
	
		return $this->updateSubscriber($user);
		
	}
  
	/**
	 * Import the system's Roles into a MailChimp grouping under the list
	 *
	 */
  public function setupGrouping() {
    
    $api = new MCAPI($this->apiKey);
    
    // Array of PW's groups
    $roles = array();
    foreach($this->roles as $role) {
      $roles[] = $role->name;
    }
    
    // Retrieve the groupings already setup in MailChimp 
    $mcGroupings = $api->listInterestGroupings($this->listId);
    
    // Find the 'Role' grouping
    $roleGroupingKey = false;
    foreach ($mcGroupings as $key => $val) {
      if ($val['name'] === 'Role') {
        $roleGroupingKey = $key;
        break;
      }
    }
    
    // Check that there is a grouping called Role - this is where we will store PW's roles
    if(is_int($roleGroupingKey)) {
      
      // Make a simple array of existing groups
      $existingGroups = array();
      foreach($mcGroupings[$roleGroupingKey]['groups'] as $group) {
        $existingGroups[] = $group['name'];
      }
      
      // Add any roles not in the existing groups as new groups
      $missingGroups = array_diff($roles, $existingGroups);
      if(count($missingGroups)) {
        foreach($missingGroups as $group) {
          $api->listInterestGroupAdd($this->listId, $group, $roleGrouping['id']);
        }
      }
      
      
    } else {
      
      $this->message("two");
      
      // If it doesn't exist create the Grouping and add all of the roles to it
      $api->listInterestGroupingAdd($this->listId, 'Role', 'hidden', $roles);
      
    }  
    
  }
	
	/**
	 * Sync all users with the list. Those not in the role are removed from the list if they appear
	 *
	 */
	public function ___syncAll($users) {
	
		foreach($users as $user) {
		
			// Check the user is in the defined group
			if(!$user->hasRole($this->role)) {
			
				// User is not in the group for the list, remove them
				$api = new MCAPI($this->apiKey);
				$api->listUnsubscribe($this->listId, $user->email, true, false, false);
				
			} else {
				
				$this->___syncUser($user);
							
			}
		
		}
		
	}
	
	/**
	 * Receive unsubscribe details from MailChimp
	 *
	 */
	public function processWebhook() {		
		
		if(!$this->input->post->type == "unsubscribe") return;
		
		$data = $this->input->post->data;
		$email = $sanitizer->email($data['email']);
		
		$user = wire('users')->find("{$this->email}=$email");
		
		if($user->id && $user->get($this->flag)) {
			$user->set($this->flag,false);
			$user->save();
		}
		
	}
	
	/**
	 * Store details in the backend
	 *
	 */
	static public function getModuleConfigInputfields(array $data) {

		$inputfields = new InputfieldWrapper();
		$inputfields->description = "Enter the details of your PayPal account below";
		
		$data = array_merge(self::$defaultConfigData, $data);
		
		$modules = wire('modules');

		$f = $modules->get('InputfieldText');
		$f->name = 'apiKey';
		$f->label = "API key";
		$f->attr('value', $data[$f->name]);
		$inputfields->add($f);
		
		$f = $modules->get('InputfieldText');
		$f->name =  'listId';
		$f->label = "List ID";
		$f->attr('value', $data[$f->name]);
		$inputfields->add($f);
		
		$f = $modules->get('InputfieldText');
		$f->name =  'email';
		$f->label = "Email field";
		$f->attr('value', $data[$f->name]);
		$inputfields->add($f);
		
		$f = $modules->get('InputfieldText');
		$f->name =  'fname';
		$f->label = "First name field";
		$f->description = "The field used to store the user's first name";
		$f->attr('value', $data[$f->name]);
		$inputfields->add($f);
		
		$f = $modules->get('InputfieldText');
		$f->name =  'sname';
		$f->label = "Surname field";
		$f->description = "The field used to store the user's surname";
		$f->attr('value', $data[$f->name]);
		$inputfields->add($f);
		
		$f = $modules->get('InputfieldText');
		$f->name =  'otherFields';
		$f->label = "Additional fields";
		$f->description = "Other user fields you would like to sync with MailChimp";
		$f->attr('value', $data[$f->name]);
		$inputfields->add($f);

		return $inputfields;

	}
	
}
